const data = {
  product: [
    {
      name: 'First Shirt',
      slug: 'fit Shirt',
      category: 'shirt',
      image: '/images/img1.jpg',
      price: '70',
      brand: 'outfitter',
      rating: '4.9',
      numReviews: '8',
      countInStock: '3',
      description: 'This is paractice purpose details',
    },
    {
      name: 'Second Shirt',
      slug: 'half Shirt',
      category: 'shirt',
      image: '/images/img2.jpg',
      price: '60',
      brand: 'outfitter',
      rating: '3.9',
      numReviews: '12',
      countInStock: '4',
      description: 'This is paractice purpose details',
    },
    {
      name: 'Third Shirt',
      slug: 'half Shirt',
      category: 'shirt',
      image: '/images/img3.jpg',
      price: '60',
      brand: 'outfitter',
      rating: '3.9',
      numReviews: '12',
      countInStock: '4',
      description: 'This is paractice purpose details',
    },
    {
      name: 'Four Shirt',
      slug: 'half Shirt',
      category: 'shirt',
      image: '/images/img4.jpg',
      price: '60',
      brand: 'outfitter',
      rating: '3.9',
      numReviews: '12',
      countInStock: '4',
      description: 'This is paractice purpose details',
    },
    {
      name: 'Third Shirt',
      slug: 'half Shirt',
      category: 'shirt',
      image: '/images/img3.jpg',
      price: '60',
      brand: 'outfitter',
      rating: '3.9',
      numReviews: '12',
      countInStock: '4',
      description: 'This is paractice purpose details',
    },
  ],
};

export default data;
